In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [ ]:
df = pd.read_csv(r'https://github.com/Yantra-Byte/Dataset/raw/main/Diabetes.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [ ]:
X=df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]
y=df[['diabetes']]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=252)
y_train

diabetes
624         0
22          1
290         0
103         0
743         1
..        ...
461         0
671         0
397         1
358         0
155         1

[537 rows x 1 columns]

In [ ]:
df.describe()

pregnancies     glucose   diastolic  ...         dpf         age    diabetes
count   768.000000  768.000000  768.000000  ...  768.000000  768.000000  768.000000
mean      3.845052  120.894531   69.105469  ...    0.471876   33.240885    0.348958
std       3.369578   31.972618   19.355807  ...    0.331329   11.760232    0.476951
min       0.000000    0.000000    0.000000  ...    0.078000   21.000000    0.000000
25%       1.000000   99.000000   62.000000  ...    0.243750   24.000000    0.000000
50%       3.000000  117.000000   72.000000  ...    0.372500   29.000000    0.000000
75%       6.000000  140.250000   80.000000  ...    0.626250   41.000000    1.000000
max      17.000000  199.000000  122.000000  ...    2.420000   81.000000    1.000000

[8 rows x 9 columns]

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((537, 8), (231, 8), (537, 1), (231, 1))

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(max_iter=500, random_state = 252)

In [ ]:
model

LogisticRegression(max_iter=500, random_state=252)

In [ ]:
model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(max_iter=500, random_state=252)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
model.predict_proba(X_test)

array([[0.84025219, 0.15974781],
       [0.57367965, 0.42632035],
       [0.85701222, 0.14298778],
       [0.89616561, 0.10383439],
       [0.67384896, 0.32615104],
       [0.16647539, 0.83352461],
       [0.10901674, 0.89098326],
       [0.57264906, 0.42735094],
       [0.95143371, 0.04856629],
       [0.95451936, 0.04548064],
       [0.35482772, 0.64517228],
       [0.24579219, 0.75420781],
       [0.69313781, 0.30686219],
       [0.96263661, 0.03736339],
       [0.67849701, 0.32150299],
       [0.89820422, 0.10179578],
       [0.56937439, 0.43062561],
       [0.90637079, 0.09362921],
       [0.88842265, 0.11157735],
       [0.94861774, 0.05138226],
       [0.97949401, 0.02050599],
       [0.9591041 , 0.0408959 ],
       [0.69878296, 0.30121704],
       [0.03656019, 0.96343981],
       [0.27369135, 0.72630865],
       [0.35555964, 0.64444036],
       [0.57983985, 0.42016015],
       [0.93010994, 0.06989006],
       [0.91099028, 0.08900972],
       [0.68155891, 0.31844109],
       [0.

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
confusion_matrix(y_test,y_pred)

array([[133,  20],
       [ 34,  44]])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83       153
           1       0.69      0.56      0.62        78

    accuracy                           0.77       231
   macro avg       0.74      0.72      0.73       231
weighted avg       0.76      0.77      0.76       231



In [ ]:
import statsmodels.api as sm

In [ ]:
X = sm.add_constant(X)

In [ ]:
X.head()

const  pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0    1.0            6      148         72       35        0  33.6  0.627   50
1    1.0            1       85         66       29        0  26.6  0.351   31
2    1.0            8      183         64        0        0  23.3  0.672   32
3    1.0            1       89         66       23       94  28.1  0.167   21
4    1.0            0      137         40       35      168  43.1  2.288   33

In [ ]:
model = sm.Logit(y, X)

In [ ]:
result = model.fit()

Optimization terminated successfully.
         Current function value: 0.470993
         Iterations 6


In [ ]:
print(result.summary())

                           Logit Regression Results                           
Dep. Variable:               diabetes   No. Observations:                  768
Model:                          Logit   Df Residuals:                      759
Method:                           MLE   Df Model:                            8
Date:                Sun, 19 Dec 2021   Pseudo R-squ.:                  0.2718
Time:                        09:45:21   Log-Likelihood:                -361.72
converged:                       True   LL-Null:                       -496.74
Covariance Type:            nonrobust   LLR p-value:                 9.652e-54
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -8.4047      0.717    -11.728      0.000      -9.809      -7.000
pregnancies     0.1232      0.032      3.840      0.000       0.060       0.186
glucose         0.0352      0.004      9.481    

As we can see in the **P** Column,the feature which is greater than 0.5% are Diastolic,Triceps,Insulin and age .These feature does not help to find the patient of Diabetes significantally.So ,we can remove these feature from model and recreate the model. 

**Recreation of Model with significant Feature**

In [ ]:
#Redifining feature 
X = df[['pregnancies', 'glucose', 'bmi',
       'dpf']]

In [ ]:
X.shape

(768, 4)

In [ ]:
#Target will be same
y = df['diabetes']

In [ ]:
# train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y, train_size = 0.7, random_state = 252)


In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((537, 4), (231, 4), (537,), (231,))

In [ ]:
model = LogisticRegression(max_iter=500, random_state = 252)

In [ ]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=500, random_state=252)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
model.predict_proba(X_test)

array([[0.85473484, 0.14526516],
       [0.59063801, 0.40936199],
       [0.8276618 , 0.1723382 ],
       [0.88248497, 0.11751503],
       [0.65946525, 0.34053475],
       [0.13756473, 0.86243527],
       [0.35484904, 0.64515096],
       [0.53019219, 0.46980781],
       [0.93297833, 0.06702167],
       [0.9537111 , 0.0462889 ],
       [0.38146074, 0.61853926],
       [0.24495497, 0.75504503],
       [0.72913838, 0.27086162],
       [0.95656176, 0.04343824],
       [0.72684492, 0.27315508],
       [0.86860925, 0.13139075],
       [0.46814154, 0.53185846],
       [0.89934509, 0.10065491],
       [0.87363773, 0.12636227],
       [0.92987593, 0.07012407],
       [0.96782264, 0.03217736],
       [0.92429525, 0.07570475],
       [0.68987687, 0.31012313],
       [0.05347079, 0.94652921],
       [0.44708382, 0.55291618],
       [0.37279495, 0.62720505],
       [0.55924959, 0.44075041],
       [0.90785971, 0.09214029],
       [0.92373708, 0.07626292],
       [0.72600393, 0.27399607],
       [0.

In [ ]:
confusion_matrix(y_test,y_pred)

array([[137,  16],
       [ 39,  39]])

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.90      0.83       153
           1       0.71      0.50      0.59        78

    accuracy                           0.76       231
   macro avg       0.74      0.70      0.71       231
weighted avg       0.76      0.76      0.75       231



We can see above in the precision column that the precion of finding the Diabetes increases 

In [ ]:
(137+39)/231

0.7619047619047619

In [ ]:
import statsmodels.api as sm

In [ ]:
X = sm.add_constant(X)

In [ ]:
X.shape

(768, 5)

In [ ]:
X.head()

const  pregnancies  glucose   bmi    dpf
0    1.0            6      148  33.6  0.627
1    1.0            1       85  26.6  0.351
2    1.0            8      183  23.3  0.672
3    1.0            1       89  28.1  0.167
4    1.0            0      137  43.1  2.288

In [ ]:
model = sm.Logit(y, X)

In [ ]:
result = model.fit()

Optimization terminated successfully.
         Current function value: 0.478064
         Iterations 6


In [ ]:
print(result.summary())

                           Logit Regression Results                           
Dep. Variable:               diabetes   No. Observations:                  768
Model:                          Logit   Df Residuals:                      763
Method:                           MLE   Df Model:                            4
Date:                Sun, 19 Dec 2021   Pseudo R-squ.:                  0.2609
Time:                        10:04:18   Log-Likelihood:                -367.15
converged:                       True   LL-Null:                       -496.74
Covariance Type:            nonrobust   LLR p-value:                 6.857e-55
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -8.4159      0.657    -12.811      0.000      -9.703      -7.128
pregnancies     0.1419      0.027      5.236      0.000       0.089       0.195
glucose         0.0338      0.003     10.112    